/******************************************************************************
 *
 * Module: UltraSonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the UltraSonic driver
 *
 * Author: Abdelrahman Youssef
 *
 *******************************************************************************/

#include <avr/io.h> /* To use the ICR1 register */
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "std_types.h"
#include <util/delay.h>

/*ICU Configuration For ICU Function used In This File */
ICU_ConfigType ICU_Configuration = {F_CPU_8,RAISING};



/*• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/




void Ultrasonic_edgeProcessing(void){


	g_edgeCount++;

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		g_edgeCount = 0 ;
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}

}

/*• Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver. */

void Ultrsonic_Init(void){

	/*initialize the icu with the given configurations*/
	ICU_init(&ICU_Configuration);

	/*mark the pointer to the function which will be called*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output pin through the
GPIO driver.*/
	GPIO_setupPinDirection(Trigger_Port, Trigger_Pin , PIN_OUTPUT);



}

/*• Description
➢ Send the Trigger pulse to the ultrasonic.*/

void Ultrasonic_Trigger(void){

	GPIO_writePin(Trigger_Port, Trigger_Pin, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(Trigger_Port, Trigger_Pin, LOGIC_LOW);
}

/*• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
 */

uint16 Ultrasonic_readDistance(void){

	uint16 distance_value = 0 ;


	/*send the trigger pulse */
	Ultrasonic_Trigger();


	distance_value = (g_timeHigh ) /57.8;
if (distance_value < 60 ){
	return distance_value+1 ;
}
	return distance_value;


}



